### ISSUE TITLE
Application

### ISSUE THREAD

**Issue by james-peterson11** [BYUCS452S2021/LanguageDev#1]
You don't have a way to post comments/articles to this page yet, so I'll try and submit my application here.

Hello, I’m James Peterson,
I like the idea of your language construction app – it seems fun and interesting. I have some mild Database experience, and can also do front end things if that the direction the project goes in. I’d be happy to contribute in any way that is needed.
Commenting on the Aspects in the assignment spec for this project – I’m posting this before the one you were thinking of are listed, but I could see Business application in the small, writers niche. There could be bigger users for companies like those who made the game MassEffect or Skyrim, but I think most of the business would probably be smaller in scale. 
Operations: I’m not sure how much upkeep something like this would require, but unless it took off big it could probably be maintained by a smaller team. It depends how many features you want to add, but the base of just storing and linking information should be simple enough.
Legal: I don’t see many problems on the legal front…
Technical: Seems like it would require decent technical knowledge. Making the DB will be simple, the difficult part will more likely be linking the information together, and creating a front end that is easily accessible to the user.
Social: I think it could find lots of use on writer forums, and other such things. I could see a interested community using this kind of device/app. I haven’t heard of a similar one as of yet, and so it seems interesting and new.

**Comment by BrtWilson** [comment]
Concluded
